### ISSUE TITLE
Add google serper tool

### ISSUE THREAD

**Issue by Undertone0809** [Undertone0809/promptulate#237]
## 🚀 Feature Request

I think we can build more tools. We can refer to the code implementation in the duck duck go search section, and also refer to the Google Serper implementation section in Langchain. It is highly recommended to read the relevant implementation code.

- https://github.com/Undertone0809/promptulate/tree/main/promptulate/tools/duckduckgo
- https://python.langchain.com/docs/integrations/tools/google_serper

We may use the following method to call tool:

```python
import promptulate as pne
from promptulate.tools.serperimport Serper


serper= Serper()
agent = pne.ToolAgent(tools=[serper])
agent.run("What's the weather in Shanghai tomorrow?")
```

**Comment by ruanrongman** [comment]
Isn't pne already perfectly compatible with the Langchain tool, and why do you need to be compatible with this tool independently?

**Comment by Undertone0809** [comment]
> Isn't pne already perfectly compatible with the Langchain tool, and why do you need to be compatible with this tool independently?

It doesn't mean we don't need it.

**Comment by Undertone0809** [comment]
@Hizeros here is a good for first issue.
