### ISSUE TITLE
Add base_url to OpenAI module

### ISSUE THREAD

**Issue by ruanrongman** [Undertone0809/promptulate#320]
By adding a base_ url  to OpenAI module can be more easily deployed, and LM Studio can also be used to connect with local large models, such as llama, for convenience

**Comment by Undertone0809** [comment]
Can you push a notebook to show how to use LM Studio in Promptulate? This is a great attempt.

**Comment by Undertone0809** [comment]
Use LLMFactory now, ChatOpenAI module is useless
