### ISSUE TITLE
A simpler way for building LLM

### ISSUE THREAD

**Issue by Undertone0809** [Undertone0809/promptulate#322]
## 🚀 Feature Request

Now we have pne.ChatOpenAI, pne.ErnieBot to invoke LLM service. Actullay, we can use a simple way to build LLM. Here is a example:

```python
import promptulate as pne

model_config = {
    "temperature": 0.0
}
llm = pne.LLMFactory(model_name="gpt-4-1106-preview", model_config=model_config)
llm("How is everything going?")
```

In this way, we can use unique way to build LLM. It's good for Agent.

## Goal

LLMFactory means that we can initialize different types of LLM model dynamically. The following points show the detail goals.

- Build LLMFactory to initialize LLM in a unique way.
- Use other framework to initialize BaseLLM, like Langchain.
- Integration the ability of Litellm, pne does not require a separate implementation model.

## Why need it?

Developers face the challenge of learning about various AI models such as ChatOpenAI, OpenAI, ErnieBot, and others, which can be seen as an additional burden. The necessity to become familiar with Prompt Engineering for each of these platforms adds to this complexity. A unified framework for interacting with these models could streamline the learning process and reduce the overhead for developers, making it easier to leverage AI tools without the need to master the intricacies of each individual system.

## Question

We may cause some questions:

Baidu AI platform, Aliyun AI platform, they can also use openai source LLM like llama. So if we use `LLMFactory.build(model_name="llama")` to create LLM. It's hard to say we need to create a LLM from Baidu or Aliyun or some else. So LLMFactory design should think consider it.

The key is we should compatible with different platforms, not specified model.

## Other

Competitive analysis is very important. Before starting, we need to conduct a survey on how other frameworks design APIs.

Framework like: langchain, modelscope-agent, litellm, llama-index ...

modelscope-agent ref: https://github.com/modelscope/modelscope-agent/blob/master/modelscope_agent/llm/llm_factory.py

## Before start

- Before starting, you can first demonstrate how other frameworks use LLM.
- Show a simple demo of how to build LLMFactory and use it.

**Comment by Undertone0809** [comment]
modelscope-agent ref: https://github.com/modelscope/modelscope-agent/blob/master/modelscope_agent/llm/llm_factory.py

**Comment by ruanrongman** [comment]
add platform parameter that can solve this problem " LLMFactory.build(model_name="llama")"

**Comment by Undertone0809** [comment]
> add platform parameter that can solve this problem " LLMFactory.build(model_name="llama")"

Detail example to show it ?

**Comment by ruanrongman** [comment]
LLMFactory.build(platform="openai",model_name="llama")

**Comment by ruanrongman** [comment]
agently LLMFactory implement `import Agently
agent_factory = Agently.AgentFactory(is_debug = False)

agent_factory\
    .set_settings("current_model", "OpenAI")\
    .set_settings("model.OpenAI.auth", { "api_key": "" })

agent = agent_factory.create_agent()`

**Comment by Undertone0809** [comment]
#502 #627 has done
