### ISSUE TITLE
adapt langchain tool

### ISSUE THREAD

**Issue by ruanrongman** [Undertone0809/promptulate#51]
移植langchain的tool生态，第一步是移植sleep和shell工具

**Comment by Undertone0809** [comment]
#52

**Comment by ruanrongman** [comment]
移植sql工具

**Comment by Undertone0809** [comment]
#67 This pr has build an implementation that enables all LangChain tools.

**Comment by Undertone0809** [comment]
> 移植sql工具

We can build an implementation though LangChain has provide the ability to do it.
