### ISSUE TITLE
erniebot SimpleChat have a very sevious bug

### ISSUE THREAD

**Issue by ruanrongman** [Undertone0809/promptulate#60]
该bug会引起erniebot无法正常使用，这是因为文心必须是偶数上下文，需要紧急修复！！！

**Comment by Undertone0809** [comment]
可以附上详细的报错信息吗

**Comment by ruanrongman** [comment]
promptulate.tips.LLMError: <LLM> could not get data correctly, reasons: {'error_code': 336003, 'error_msg': 'the length of messages must be an odd number', 'id': 'as-r2m1yiqv5z'}
