### ISSUE TITLE
Add Stream JSON parser

### ISSUE THREAD

**Issue by Undertone0809** [Undertone0809/promptulate#625]
## 🚀 Feature Request

Currently, we cannot enable stream if setting output schema. Eg:

```python
from typing import List
import promptulate as pne
from pydantic import BaseModel, Field


class LLMResponse(BaseModel):
    provinces: List[str] = Field(description="All provinces in China")


response: LLMResponse = pne.chat(
    messages="Please tell me all provinces in China.",
    output_schema=LLMResponse,
    model="gpt-4-1106-preview",
    stream=True,
)
print(response.provinces)
```

![image](https://github.com/Undertone0809/promptulate/assets/72488598/b5e5c760-beda-40d4-81ea-55f835ee90f7)

Need to build a json parser to parse stream type json data like this:

![image](https://github.com/Undertone0809/promptulate/assets/72488598/afee11d6-15c0-4298-a9d1-c9e81e86771b)

**Comment by Undertone0809** [comment]
Here to see how to solve: https://twitter.com/yetone/status/1784487439610126426

**Comment by Undertone0809** [comment]
Need to add an doc example to show how to use stream mode.

**Comment by Undertone0809** [comment]
https://mp.weixin.qq.com/s/gMdQBlTdvGbhzi_NL3HGXQ

**Comment by ruanrongman** [comment]
https://github.com/half-pie/half-json/blob/master/half_json/json_util.py

**Comment by Undertone0809** [comment]
ref #828
