### ISSUE TITLE
add humanfeedback tool

### ISSUE THREAD

**Issue by ruanrongman** [Undertone0809/promptulate#68]
添加这个工具可以使得agent变得更具交互性，用于智能家居场景，能更好满足需求，下面是添加后的结果
Question: 现在你是一个智能音箱，我现在感觉好暗
Thought:
I need to find a way to help the user with their lighting issue. I could potentially use the IoT Switch MQTT tool to control the lights in the room. However, I should confirm with the user if they want me to do that or if they have another solution in mind.

Action: human_feedback
Action Input: "Would you like me to adjust the lighting in the room for you?"

Observation: yes
Thought: The user wants me to adjust the lighting in the room. I can use the IoT Switch MQTT tool to do that.

Action: Iot_Switch_Mqtt
Action Input: "Turn on the lights"

Observation: ok
Thought: The lights have been turned on. The user should now have better lighting.

Final Answer: The lights in the room have been turned on.

[DEBUG] 2023-09-08 17:23:58 [pne hook] hooks <('Agent', 'on_agent_result')> mounted_obj <ToolAgent> call hook: <[BaseHookSchema(hook_name='on_agent_result', callback=<function StdOutHook.handle_agent_result at 0x0000015223F73CA0>, component_type='Agent')]>
[Agent Result]  The lights in the room have been turned on.
Agent End.

**Comment by ruanrongman** [comment]
也许增加对agent的角色设定可以提升交互效果

**Comment by Undertone0809** [comment]
可以具体描述一下角色设定的意思吗？我的理解是在system prompt的基础上在加一些custom system prompt。

**Comment by ruanrongman** [comment]
我也是这么想的，在system prompt的基础上在加一些custom system prompt，就像那个gpt小镇项目。
